apiVersion: v1
kind: Secret
metadata:
  name: {{ include "discovery-agent.fullname" . }}-secrets
  labels:
    {{- include "discovery-agent.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.discoveryAgentToken }}
  discovery-agent-token: {{ .Values.secrets.discoveryAgentToken | b64enc | quote }}
  {{- end }}
